### ISSUE TITLE
[Bug]: Long calculation time

### ISSUE THREAD

**Issue by jvandorstrhdhv** [Project-OMOTES/user_feedback#21] opened 2024-01-11 14:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What happened?

Discussed with Femke and Jim

Calculation time of my network (150 heating demand connections) was 42 minutes. 
The ESDL file is added below. 

[AGRO Energy with return network - txt.txt](https://github.com/Project-OMOTES/user_feedback/files/13904353/AGRO.Energy.with.return.network.-.txt.txt)

### Steps to reproduce the problem

EDSL file is added (before calculation)

### What should have happened?

Shorter calculation time

### What browsers do you use to access the UI?

Google Chrome

**Comment by jimrojerTNO** [comment] 2024-01-16 07:06
@KobusVanRooyen this is the issue relating to testing if establishing the connection is taking long.

**Comment by KobusVanRooyen** [comment] 2024-06-10 07:10
@samvanderzwan:
- this is labeled as a bug, but it is not a bug. Please change this.
- this was investigated and improvements were made in the MVP version (0.1.3.1). The same network now solves about 19% faster than before. 
- this issue can be closed

**Comment by KobusVanRooyen** [comment] 2024-08-14 13:25
@samvanderzwan can you please close this item

**Closed** 2024-09-16 07:29 UTC
